# Generated by Django 4.2.2 on 2023-06-15 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_productpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productpage',
            new_name='productdb',
        ),
    ]
