# Generated by Django 4.2.2 on 2023-06-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_productdb_pricerange'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
