# Generated by Django 4.2.2 on 2023-07-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_sign_indb'),
    ]

    operations = [
        migrations.CreateModel(
            name='transactiondb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnumber', models.IntegerField(blank=True, null=True)),
                ('monthyear', models.CharField(blank=True, max_length=100, null=True)),
                ('cvvcode', models.IntegerField(blank=True, null=True)),
                ('cardname', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
