# Generated by Django 4.2.2 on 2023-07-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_transactiondb'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondb',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
