# Generated by Django 4.2.2 on 2023-06-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_productdb_email_productdb_image_productdb_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='traveldate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
