# Generated by Django 4.2.2 on 2023-06-20 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_productdb_traveldate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdb',
            name='email',
        ),
    ]
