# Generated by Django 4.2.2 on 2023-06-20 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_productdb_mobile_remove_productdb_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdb',
            old_name='price',
            new_name='pricerange',
        ),
    ]
