# Generated by Django 4.2.2 on 2023-07-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_productdb_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdb',
            name='pricerange',
        ),
        migrations.AddField(
            model_name='productdb',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
